services:
  postgres:
    image: postgres:16
    container_name: invest-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: investments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: invest-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DSN: host=postgres user=postgres password=postgres dbname=investments port=5432 sslmode=disable
      PORT: 8080
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: