version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: invest-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: invest-tracker
    volumes:
      - mongo-data:/data/db

  # backend:
  #   build: .
  #   container_name: invest-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     MONGO_URI: mongodb://mongo:27017/invest-tracker
  #     MONGO_DB: invest-tracker
  #     MONGO_COLLECTION: investments
  #     PORT: 8080
  #   depends_on:
  #     - mongo
  #   restart: unless-stopped

volumes:
  mongo-data: